# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2.1
orbs:
  codecov: codecov/codecov@1.1.3
jobs:
  build73:
    docker:
      - image: circleci/php:7.3-node-browsers
    steps:
      - checkout

      - run: sudo apt update
      - run: sudo docker-php-ext-install zip sockets

      # Download and cache dependencies.
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            # Fallback to using the latest cache if no exact match is found.
            - v1-dependencies-

      - run: composer install -n --prefer-lowest

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor

      - run: ./vendor/bin/phpcs .
      - run: XDEBUG_MODE=coverage ./vendor/bin/phpunit --coverage-clover=coverage.xml

      - codecov/upload:
          file: ./coverage.xml
  build8:
    docker:
      - image: circleci/php:8.0-node-browsers
    steps:
      - checkout

      - run: sudo apt update
      - run: sudo docker-php-ext-install zip sockets

      # Download and cache dependencies.
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            # Fallback to using the latest cache if no exact match is found.
            - v1-dependencies-

      - run: composer install -n --prefer-stable

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor

      - run: ./vendor/bin/phpcs .
      - run: XDEBUG_MODE=coverage ./vendor/bin/phpunit --coverage-clover=coverage.xml

      - codecov/upload:
          file: ./coverage.xml
